### ISSUE TITLE
Create match and round tables for multiplayer

### ISSUE THREAD

**Issue by tgpholly** [tgpholly/Binato#11]
Multiplayer needs to be tracked so previous games, what maps were played, player scores, etc can be retrieved and shown on a round by round basis.

This would also make it so that file being used for match ids can be nuked.

**Comment by tgpethan** [comment]
Tables have been created, server needs to write to said tables now (live instance already uses the matches table but match rounds are still not recorded)

**Comment by tgpethan** [comment]
This is now done, I'll commit it tomorrow (if I don't forget)

**Comment by tgpethan** [comment]
I forgor 💀

**Comment by tgpholly** [comment]
I think this is done with da3dd4c as I accidentally bundled a load of changed in with it
