### ISSUE TITLE
Failed to release mysql connection Error: Access denied for user 'u15029_osu'@'46.72.x.x' to database 'osu'

### ISSUE THREAD

**Issue by kolesto65** [tgpholly/Binato#13]
16|osusrv  | Failed to release mysql connection Error: Access denied for user 'u15029_osu'@'46.72.x.x' to database 'osu'
16|osusrv  |     at Packet.asError (/srv/gameap/b/osusrv/node_modules/mysql2/lib/packets/packet.js:728:17)
16|osusrv  |     at ClientHandshake.execute (/srv/gameap/b/osusrv/node_modules/mysql2/lib/commands/command.js:29:26)
16|osusrv  |     at PoolConnection.handlePacket (/srv/gameap/b/osusrv/node_modules/mysql2/lib/connection.js:456:32)
16|osusrv  |     at PacketParser.onPacket (/srv/gameap/b/osusrv/node_modules/mysql2/lib/connection.js:85:12)
16|osusrv  |     at PacketParser.executeStart (/srv/gameap/b/osusrv/node_modules/mysql2/lib/packet_parser.js:75:16)
16|osusrv  |     at Socket.<anonymous> (/srv/gameap/b/osusrv/node_modules/mysql2/lib/connection.js:92:25)
16|osusrv  |     at Socket.emit (node:events:527:28)
16|osusrv  |     at addChunk (node:internal/streams/readable:324:12)
16|osusrv  |     at readableAddChunk (node:internal/streams/readable:297:9)
16|osusrv  |     at Socket.Readable.push (node:internal/streams/readable:234:10) {
16|osusrv  |   code: 'ER_DBACCESS_DENIED_ERROR',
16|osusrv  |   errno: 1044,
16|osusrv  |   sqlState: '42000',
16|osusrv  |   sqlMessage: "Access denied for user 'u15029_osu'@'46.72.x.x' to database 'osu'",
16|osusrv  |   sql: undefined
16|osusrv  | }

I use external DB running on MariaDB v 5.5.68 .
In config as a DB address i use my external DB's address, but in error it shows that it tried to connect to address that my current server uses, not the external one
OS: Ubuntu 20.04

**Comment by tgpholly** [comment]
happens to the best of us
